const tutorials = [
  {
    href: "https://medify-vapi.vercel.app/",
    title: "Project 1: Medify",
    description: "Consult doctors with voice agents AI advice and diagnosis",
    shortDescription:
      "Consult doctors with voice agents AI advice and diagnosis",
    imageUrl: "/images/medic.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://blog-wes.vercel.app/",
    title: "Project 1: Blog Deluxe",
    description: "Blog Deluxe",
    shortDescription: "Blog Deluxe",
    imageUrl: "/images/blog.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://discord-clone-47vy.vercel.app/",
    title: "Project 1: Discord Clone",
    description:
      "Discord: Disclord clone using video or audio and generating channels",
    shortDescription:
      "Discord: Disclord clone using video or audio and generating channels",
    imageUrl: "/images/discord.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://resonance-alpha-five.vercel.app/",
    title: "Project 1: Resonance",
    description:
      "Resonance: use build in voices, or create your own recording of your voice and use it for text to speech",
    shortDescription:
      "Resonance: use build in voices, or create your own recording of your voice and use it for text to speech",
    imageUrl: "/images/resonance.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://invoice-jan.vercel.app/",
    title: "Project 1: Invoice",
    description: "Invoice: Email notification graphs, mark as paid etc.",
    shortDescription: "Invoice: Email notification graphs, mark as paid etc.",
    imageUrl: "/images/invoice1.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://teamflow-pi-beige.vercel.app/",
    title: "Project 1: TeamFlow",
    description: "TeamFLow: Similar to slack with AI driven features",
    shortDescription: "TeamFLow: Similar to slack with AI driven features",
    imageUrl: "/images/tailflow.jpg",
    alt: "WesleyTech Shop",
  },

  {
    href: "https://nodebase-gamma.vercel.app/",
    title: "Project 1: n8n",
    description: "Nodebase : AI driven app clone similar to n8n",
    shortDescription: "AI driven app clone similar to n8n.",
    imageUrl: "/images/n8n.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://polaris-five-zeta.vercel.app/",
    title: "Project 1: Polaris",
    description:
      "Polaris : AI driven app that is similar to cursur where you prompt an app idea and it builds it.",
    shortDescription:
      "AI driven app that is similar to cursur where you prompt an app idea and it builds it.",
    imageUrl: "/images/polaris.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://new-tube01.vercel.app/",
    title: "Project 1: CodeBox 2.0",
    description: "CodeBox 2.0 : Do courses learning about coding",
    shortDescription: "You tube clone with extra AI abilities",
    imageUrl: "/images/newtube.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://codebox2-0-beryl.vercel.app/",
    title: "Project 1: CodeBox 2.0",
    description: "CodeBox 2.0 : Do courses learning about coding",
    shortDescription: "CodeBox 2.0",
    imageUrl: "/images/code.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-agent-tubeguri.vercel.app/",
    title: "Project 1: AI Agents n8n",
    description: "AI Agents n8n",
    shortDescription: "AI Agents n8n",
    imageUrl: "/images/agents8.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-fusion-lab-one.vercel.app/",
    title: "Project 1: AI-Fusion App",
    description: "AI-Fusion App",
    shortDescription:
      "AI-Fusion App: create outputs for multiple AI models at the same time",
    imageUrl: "/images/aifusion.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://meetai-ashy.vercel.app/",
    title: "Project 1: Meet-AI",
    description: "Meet-AI",
    shortDescription: "Meet-AI: Create multiple agents and chats",
    imageUrl: "/images/agent.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-website-generator-eta.vercel.app/",
    title: "Project 1: Website-Generator",
    description: "Website-Generator",
    shortDescription:
      "Website-Generator: generated by AI by your prompt and fully customizable",
    imageUrl: "/images/web.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://echo-tutorial-web-lilac.vercel.app/",
    title: "Project 1: ECHO: Customer Vapi Voice agent, knowledge base upload",
    description: "AI Adverts",
    shortDescription: "ECHO: Customer Vapi Voice agent, knowledge base upload",
    imageUrl: "/images/echo.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-advertising-video-image.vercel.app/app",
    title: "Project 1: AI-Adverts",
    description: "AI Adverts",
    shortDescription:
      "AI Adverts generate your own AI adverts with image and video options and avatar fun",
    imageUrl: "/images/Adverts.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-medical-agent-hazel.vercel.app/",
    title: "Project 1: AI Medical Voice Agent",
    description: "AI Medical Voice Agent",
    shortDescription: "AI Medical Voice Agent",
    imageUrl: "/images/doc.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://car-app-two-orpin.vercel.app/",
    title: "Project 1: Car Market",
    description: "Car Market",
    shortDescription: "Car Market",
    imageUrl: "/images/car2.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-career-coach-jade.vercel.app/",
    title: "Project 1: AI-Career-Coach",
    description: "AI-Career-Coach",
    shortDescription:
      "AI-Career-Coach: Get links and direction on your career path",
    imageUrl: "/images/carreers.jpg",
    alt: "WesleyTech Shop",
  },
  // {
  //   href: "https://hulu-clone-blue-one.vercel.app/",
  //   title: "Project 1: Hulu Clone",
  //   description: "Hulu Clone",
  //   shortDescription: "Hulu Clone",
  //   imageUrl: "/images/hulu.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://ai-recruiter-teal.vercel.app/",
  //   title: "Project 5: AI Recruiter ",
  //   description: "Automated AI Interviews",
  //   shortDescription:
  //     "AI Recruiter: Schedule a Job description and the requirements and get a full interview based on your prompt and duration with decision making on whether to hire the candidate as well as a report of the full conversatino and answers and ratings",
  //   imageUrl: "/images/ai-recruitors.jpg",
  //   alt: "WesleyTech Shop",
  // },
  {
    href: "https://mock-interview-zeta-amber.vercel.app/",
    title: "Project 8: Mock Interview Practice ",
    description: "Generate questions on your next interview you choose,",
    shortDescription:
      "Mock Interviews : Prompt your next interview and the roles and experience you have, and 5 questions will be designed to help you practice with answers and complete review of how you did with ratings and the correct answers",
    imageUrl: "/images/ai-interviews.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-youtube-short-video-gen-beryl.vercel.app/",
    title: "Project 9: Short Video ",
    description: "Generate a Short Video with your own styles",
    shortDescription:
      "Short Videos : Using Next JS With AI Gemmini Model, Generate a Video with captions and style of your own , with a story of your own and link it all to share with your friends for inspiration and creation of artwork",
    imageUrl: "/images/ai-shortvideos.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://study-material-ashy.vercel.app/",
    title: "Project 10: Studying Material Generator ",
    description: "Generate a almost anthing To Study With",
    shortDescription:
      "Study Material Generator: Using Next JS With AI Gemmini Model, Generate FlashCards, Quizzes, Q and A and Notes To Study On any Topic",
    imageUrl: "/images/ai-education-resources.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://wireframe-code.vercel.app/",
    title: "Project 11: Code Generator For The UI - Any Layout ",
    description: "Generate a almost anthing from multiple options",
    shortDescription:
      "Code UI Generator: Using Next JS Multiple AI models of your choice, to test out different creations, Upload a image and a prompt of the layout of a website, and BOOM",
    imageUrl: "/images/ai-code-ui.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://ai-course-generator-awesomeness.netlify.app/",
    title: "Project 12: Course Builder - Almost Anthing Educational AI ",
    description: "Generate a almost anthing from multiple options",
    shortDescription:
      "Course Builder: Using Next JS 14 and GEMMINI AI to produce almost any course from programming, health , and the other topic creative which can be anthing, generate a course with chapters and a Utube video assigned for each chapter automatically, fully editable with a upload image of your choice and chapters , difficulty level, and hours chosen by you, etc... and many more, share with your friends and spread the knowlege of all your ideas and courses",
    imageUrl: "/images/ai-course.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://spectacular-ai-content-builder.netlify.app/",
    title: "Project 13: Content Builder - Almost Anthing AI ",
    description: "Generate a almost anthing from multiple options",
    shortDescription:
      "Content Builder: Using Next JS 14 and GEMMINI AI to produce almost any infomation from diets, meal ideas, Lyric writing, Song chords, Teacher lesson plans, Travel Itinary, Counseling, Business Ideas, etc... and many more",
    imageUrl: "/images/content-builder.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://logo-generator-ai-ashy.vercel.app/",
    title: "Project 14: Logo Generator AI",
    description:
      "Generate a origional Logo for your Business or Service, Website or Idea",
    shortDescription:
      "Logo Generator: Using Next JS 14 and Clerk Authentication, send a prompt and idea and let AI do the rest, select your color palette, and style and generate either a paid version or a free version, the difference is just time",
    imageUrl:
      "https://github.com/Gotcha1001/My-Images-for-sites-Wes/blob/main/yyyy.jpg?raw=true",
    alt: "WesleyTech Shop",
  },
  // {
  //   href: "https://interior-design-ruby-two.vercel.app/",
  //   title: "Project 15: Interior Decorator AI",
  //   description: "Transform any room in your house into your chosen choice",
  //   shortDescription:
  //     "Interior Decorator AI: Using Next JS 14 and Clerk Authentication, upload any image of your house and transform it into the style of your choice within seconds and share it with your friends and family, or use it as a plan for the future",
  //   imageUrl: "/images/interior-design.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://kids-stories-ai.vercel.app/",
  //   title: "Project 16: AI Kids Stories Generater",
  //   description: "Generate any type of form with AI",
  //   shortDescription:
  //     "AI Kids Story: Using Next JS 14 and Clerk Authentication, create various stories for various age groups, and story types, and animated image options, read your stories and displayed in a beautiful turn the page book, and share it directly with friends and social media,  using Google Gemini AI story generation, and Replicate AI Image generation, so much fun for the family",
  //   imageUrl: "/images/kids-story.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://ai-form-ten.vercel.app/",
  //   title: "Project 17: AI Form Generater",
  //   description: "Generate any type of form with AI",
  //   shortDescription:
  //     "AI Form Generator: Using Next JS 14 and Clerk Authentication, and SHADCN for components, create any form for cooking, self checks, classes, jobs, anything with Google AI and alter your forms as you will, with rich themes or backgrounds, edit fields, and share your link with anyone to fill out and download the filled form in Excel",
  //   imageUrl: "/images/ai-form.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://reflect-private-journal.vercel.app/",
  //   title: "Project 18: Digital Journal App",
  //   description: "Digital Journal App",
  //   shortDescription:
  //     "Digital Journal App: Using Next JS 15 and Clerk Authentication, and SHADCN for components, Filtering, Rich Text Editor, with Collections for your Categories, then you can add your entries, add Video Urls, Images, Utilizing a API to generate images based on your mood you select, with amazing slide in animations using Framer Motion",
  //   imageUrl: "images/digital-journal.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://workflow-jira-clone.vercel.app/",
  //   title: "Project 19: Jira Clone WorkFlow App",
  //   description: "Jira Clone WorkFlow App",
  //   shortDescription:
  //     "Jira Clone WorkFlow: Using Next JS 15 and Clerk Authentication, and SHADCN for components, Filtering, Creating Projects and Sprints and setting start and end dates of the task, and priority settings, with admin rights to only alter them , with amazing animations and functionality",
  //   imageUrl: "/images/jira-clone.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://social-media-art.vercel.app/",
  //   title: "Project 21: Social Cloud App",
  //   description: "Social Cloud App",
  //   shortDescription:
  //     "Social Cloud App: Using Next JS 15 and Clerk Authentication, and SHADCN for components, A mini version of Facebook, with the ability to create posts, other users can comment like, Search for Users, Add Stories, cool animations and Rad UI annimations, Using Server Actions and the latest coding technology",
  //   imageUrl: "/images/social-media.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://finance-track-wine.vercel.app/",
  //   title: "Project 22: Finance Tracker",
  //   description: "Finance Tracker",
  //   shortDescription:
  //     "Finance Tracker: Using Next JS 15 and Clerk Authentication, and SHADCN for components, this one is a masterpiece of mathematical equations and has such a functionality that everybody can use in their daily lives, to save money and keep track of all their expenses and also print out their expenses at any time for reference",
  //   imageUrl: "/images/budget.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://sonny-ecommerce.vercel.app/",
  //   title: "Project 23: Ecommerce Site SHOPNOW",
  //   description: "Ecommerce Site SHOPNOW",
  //   shortDescription:
  //     "Ecommerce Site SHOPNOW: Using Next JS 15 and Clerk Authentication, and STRIPE, coupons, and amazing search functionality and for the owner of the website , an amazing new technology called STUDIO , to add products, alter the whole website so easily and live as well...... AMAZING SANITY for the backend that makes it fun and so easy",
  //   imageUrl: "/images/shop-now.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://instagram-fun-mauve.vercel.app/",
  //   title: "Project 24: Instagram Clone with a twist",
  //   description: "Instagram Clone with a twist",
  //   shortDescription: "Instagram fun...",
  //   imageUrl: "/images/instagram.jpg",
  //   alt: "WesleyTech Shop",
  // },
  // {
  //   href: "https://multistore-dawid-map.vercel.app/",
  //   title: "Project 24: Multistore Ad App",
  //   description: "Multistore Ad App",
  //   shortDescription:
  //     "Multistore Ad App: Login and Create any ad you wish wish a location of your product, where the users can search products under their area through Google Maps, Post ads, edit, delete with beautiful filtering in price, location and categories",
  //   imageUrl: "/images/multi-store.jpg",
  //   alt: "WesleyTech Shop",
  // },
  {
    href: "https://video-subtitles.onrender.com/",
    title: "Project 25: Video Captions App",
    description: "Video Captions App",
    shortDescription:
      "Video Captions App: Upload a video and apply captions to the speech and alter the colors and font size and download it for your usage",
    imageUrl: "/images/captions.jpg",
    alt: "WesleyTech Shop",
  },
  // {
  //   href: "https://calandar-seven.vercel.app/",
  //   title: "Project 26: Calandar Clone App",
  //   description: "Digital Google Appointsments App",
  //   shortDescription:
  //     "Calendar Clone App: Using Next JS 14 and Clerk Authentication, and SHADCN for components, Make events and book appointments that automatically get sent to your google calendar and emails get sent to the user trying to book a meeting with you in your certain slots",
  //   imageUrl: "/images/calendar.jpg",
  //   alt: "WesleyTech Shop",
  // },
  {
    href: "https://tastyfood-ordering-app-frontend.onrender.com/",
    title: "Project 27: Multi Restaurant App",
    description: "Multi Restaurant App",
    shortDescription:
      "Mutil Restaurant App: Authentication with Auth0, Create a Restaurant, add Products, and Delivery Fees, and Stripe Payment",
    imageUrl: "/images/tasty-food.jpg",
    alt: "WesleyTech Shop",
  },
  {
    href: "https://exercise-one.pages.dev/",
    title: "Project 28: Exercise App",
    description: "Exercise App",
    shortDescription:
      "Exercise App: Very simple application with mainly UI functionality but utilizing Framer Motion with all its annimations beuatifully",
    imageUrl: "/images/gym.jpg",
    alt: "Exercise App",
  },
  {
    href: "https://car-demo-rbo1.vercel.app/",
    title: "Project 29: Rent A Car Demo Project",
    description: "Rent A Car Demo Project",
    shortDescription:
      "Rent A Car Demo: A nice Demo Project to view various Cars, consuming a API with multiple search functionlity and details of each car in the Modal POPUPS......",
    imageUrl: "/images/car.jpg",
    alt: "WesleyTech Shop",
  },
];

export default tutorials;
